### PR TITLE
Make filename an optional parameter

### PR DESCRIPTION
**Pull request by tomers**

### CODE REVIEW

**Comment by fim** [comment]
Why?

**Comment by tomers** [comment]
My use case is an ICap which filters based on URLs. I need to test it and I don't care about the body. It will be used for regular browsing.
Seems like all ICaps in use today are for ClamAV ;-)

BTW I'll appreciate that in case you merge this one, that you'll release a new version, so it'll be available in `pip`. Thanks.

**Comment by fim** [comment]
Can you provide an example use case so I can better understand what you mean?

**Comment by tomers** [comment]
```python3
import icapclient
from pprint import pprint

conn = icapclient.ICAPConnection('localhost', port=1344)
conn.request('REQMOD', url='http://www.google.com', service='servicename')
resp = conn.getresponse()
print(resp.icap_status)
print(resp.icap_reason)
pprint(resp.icap_headers)
```

**Comment by tomers** [comment]
This works with Ubuntu's `c-icap` package (https://packages.ubuntu.com/xenial/c-icap):
```
$ c-icap-client -p 1344 -s servicename -req http://google.com
ICAP server:localhost, ip:127.0.0.1, port:1344

No modification needed (Allow 204 response)
```

**Pull request merged**
