### PR TITLE
Support passing HTTP method

### PR DESCRIPTION
**Pull request by tomers**
Hi, thanks for releasing a new version! I would be grateful if you could do the same now...

### CODE REVIEW

**Comment by fim** [comment]
Hey, it'd be nice if you could an idea of what's the end state you'd like to get to and batch all your changes in one PR along with a write up of what this new feature provides.

As is, it seems like these are small one off changes that do not benefit the project as a whole, at least not with a specific direction in mind and also require time and effort to merge/release.

If this is an ongoing effort, it'd make sense for you to use your own fork and implement all the changes needed there and then create a PR for everything at once rather than for each addition individually. 

Hope this makes sense

**Comment by tomers** [comment]
Hi, any news on this? I'll be grateful if you could you review this. Thanks a lot!

**Comment by fim** [comment]
Please check my previous comment

**Comment by tomers** [comment]
Hi Serafeim,
There is no great plan here. I have no further changes that I plan to ask for.
I use the ICap client to test my icap, which happen to be more generic from what the current client expected, which is to POST a file to the ICap. In my case there is no file involved, and the HTTP method might not be a POST action. I was surprised to see the HTTP method hard-coded in the client's code, but I guessed nobody ever needed it up until this point.
I did not notice this when I posted my first merge. In any case I did not imagine it should pose any issue for the maintainer to release a minor version update, and also I am used to submit different changes in a separate PRs, which I did.

I hope you'll agree to merge this rather simple commit which makes the tool more flexible.

**Comment by fim** [comment]
I clicked and merged this by mistake so I had to roll back master branch.

This won't even compile. I will get back with a more detailed  review but feel free to fix and submit a new PR along with a usability test to make sure it's doing what's expected.

**Pull request merged**
